# SafePrice Simulator

### Import Libraries

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Reading Raw Datasets

In [3]:
root_path = os.path.dirname(os.getcwd())

raw_data_path = os.path.join(root_path, "datasets/raw")
raw_datasets = os.listdir(raw_data_path)

print(raw_datasets)

['online_retail_II.xlsx', 'Retail Prices Index.xlsx']

#### Read Retail Dateset

In [ ]:
online_retail_df_2009_2010 = pd.read_excel(os.path.join(raw_data_path, raw_datasets[0]), sheet_name='year_2009_2010')

online_retail_df_2009_2010.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
online_retail_df_2010_2011 = pd.read_excel(os.path.join(raw_data_path, raw_datasets[0]), sheet_name='year_2010_2011')

online_retail_df_2010_2011.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [10]:
retail_df = pd.concat([online_retail_df_2009_2010, online_retail_df_2010_2011], ignore_index=True)
retail_df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [9]:
print(len(online_retail_df_2009_2010))
print(len(online_retail_df_2010_2011))
print(len(retail_df))

525461
541910
1067371

#### Read Retail Prices Index Dateset

In [23]:
retail_price_index_df = pd.read_excel(os.path.join(raw_data_path, raw_datasets[1])).iloc[972:1008]
retail_price_index_df.head()

        Title Retail Prices Index: Long run series: 1800 to 2024: Jan 1974=100
972  2009 JAN                                              828.8
973  2009 FEB                                                834
974  2009 MAR                                              833.6
975  2009 APR                                              834.4
976  2009 MAY                                              839.5

In [24]:
retail_price_index_df.rename(columns={
    'Title': 'Date',
    'Retail Prices Index: Long run series: 1800 to 2024: Jan 1974=100': 'Retail Price Index'
}, inplace=True)

In [25]:
retail_price_index_df.head()

         Date Retail Price Index
972  2009 JAN              828.8
973  2009 FEB                834
974  2009 MAR              833.6
975  2009 APR              834.4
976  2009 MAY              839.5

### Data Preparation

In [26]:
retail_df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [ ]:
retail_df